language: python

# python-rpm is not available through pip, so we need to get it with
# apt-get and configure the virtualenv to use system site packages. As
# long as that's the case, we need to stick with Python 2.7 only.

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-enchant
      - python-magic

install:
  - sudo apt-get update -qq
  # https://github.com/travis-ci/apt-package-whitelist/issues/1696
  - sudo apt-get install -qq rpm python-rpm rpm2cpio
  - pip install pytest flake8 flake8-import-order

script:
  - make check
