language: python

# python-rpm is not available through pip, so we get it with apt-get
# and configure the virtualenv to use system site packages. As long as
# that's the case, we need to stick with the system installed Python
# versions only. Unfortunately as python3-rpm is not available even
# for Trusty, that means 2.7 only for now.

dist: trusty

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-enchant
      - python-magic

install:
  # https://github.com/travis-ci/apt-package-whitelist/issues/1696
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-rpm rpm rpm2cpio
  - pip install pytest flake8 flake8-import-order hacking

script:
  - make check
